name: "mosaico"
services:
  
  database:
    image: postgres:18
    container_name: postgres
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: mosaico
    networks:
      - mosaico
    volumes:
      - pg-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U  postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  mosaicod:
    image: ghcr.io/mosaico-labs/mosaicod:latest
    # There are other available predefined tags that you can use.
    container_name: mosaicod
    networks:
      - mosaico
    # Here you can list any additional command line options for `mosaicod`. 
    # In this example, we configure the server to use the local filesystem for 
    # storage, which is mounted to the `/data` directory in the container. 
    # This allows you to persist data across container restarts and easily access 
    # it from the host machine. Additional environment variables can be set here to configure 
    # the daemon's behavior.
    environment:
      MOSAICOD_DB_URL: postgresql://postgres:password@db:5432/mosaico
      MOSAICOD_STORE_ENDPOINT: file:///
      MOSAICOD_STORE_BUCKET: data
    volumes:
      - mosaico-data:/data
    command: | 
      run --host 0.0.0.0 --port 6726 --log-level info 
    depends_on:
      database:
        condition: service_healthy
    ports:
    # Remove `127.0.0.1` to expose this service to external networks. 
    # By default, this configuration restricts access to the local machine for security reasons. 
    # If you need to access the server from other machines on the network, 
    # you can modify the port mapping to allow external connections.
      - "127.0.0.1:6726:6726"

volumes:
  pg-data:
  mosaico-data:

networks:
  mosaico: