name: Static Analysis

on: 
  push:
    branches: ["master"]
    paths:
      - "**.py"
      - "**/pyproject.toml"
      - "**/poetry.lock"
  pull_request:
    branches: ["master"]
    paths:
      - "**.py"
      - "**/pyproject.toml"
      - "**/poetry.lock"

permissions:
  contents: read

jobs:
  static-analysis:
    name: "Static analysis"
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3 # executes ruff check by default (next line could be dropped)
      - run: ruff check
      - run: ruff format --check


