name: Static Analysis

on: 
  push:
    branches: ["master"]
    paths:
      - "**.py"
      - "**/pyproject.toml"
      - "**/poetry.lock"
  pull_request:
    branches: ["master"]
    paths:
      - "**.py"
      - "**/pyproject.toml"
      - "**/poetry.lock"

permissions:
  contents: read

jobs:
  static-analysis:
    name: "Static analysis"
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v6
      
      - name: Python SDK Lint
        run: |
          pipx install ruff
          ruff format --check mosaico-sdk-py
          ruff check mosaico-sdk-py

